import type { ExtShvaParams } from '../types/ExtShvaParams.ts'
import type { ToZod } from '@kubb/plugin-zod/utils/v4'
import { z } from 'zod'

export const extShvaParamsSchema: z.ZodObject<import("/home/m/dev/git/cardcom-ts-sdk/node_modules/@kubb/plugin-zod/dist/utils/v4").ZodShape<ExtShvaParams>, "passthrough"> = z.object({
  HaveRecipient: z.boolean().optional(),
  Status1: z.int().optional(),
  CardNumber5: z.string().nullable().nullish(),
  Sulac25: z.string().nullable().nullish(),
  JParameter29: z.string().nullable().nullish(),
  Tokef30: z.string().nullable().nullish(),
  Sum36: z.int().optional(),
  SumStars52: z.string().nullable().nullish(),
  ApprovalNumber71: z.string().nullable().nullish(),
  FirstPaymentSum78: z.string().nullable().nullish(),
  ConstPayment86: z.string().nullable().nullish(),
  NumberOfPayments94: z.string().nullable().nullish(),
  AbroadCard119: z.string().nullable().nullish(),
  CardTypeCode60: z.string().nullable().nullish(),
  Mutag24: z.string().nullable().nullish(),
  CardOwnerName: z.string().nullable().nullish(),
  CardToken: z.string().nullable().nullish(),
  CardHolderIdentityNumber: z.string().nullable().nullish(),
  CardName: z.string().nullable().nullish(),
  CreditType63: z.string().nullable().nullish(),
  DealType61: z.string().nullable().nullish(),
  ChargType66: z.string().nullable().nullish(),
  SapakMutav: z.string().nullable().nullish(),
  BinId: z.int().optional(),
  DealDate: z.date().optional(),
  ExternalPaymentVector: z.int().nullable().nullish(),
  ExternalPaymentID: z.string().nullable().nullish(),
  CustomFields: z.array(z.string()).nullable().nullish(),
  TerminalNumber: z.int().optional(),
  InternalDealNumber: z.int().optional(),
  CouponNumber: z.string().nullable().nullish(),
  CardOwnerPhone: z.string().nullable().nullish(),
  FirstCardDigits: z.int().nullable().nullish(),
  Uid: z.string().nullable().nullish(),
}) as unknown as ToZod<ExtShvaParams>