import type { InvHeadLineDto } from '../types/InvHeadLineDto.ts'
import type { ToZod } from '@kubb/plugin-zod/utils/v4'
import { z } from 'zod'

export const invHeadLineDtoSchema = z.object({
  TotalNoVatNIS: z.number().optional(),
  TotalIncludeVATNIS: z.number().optional(),
  VATOnlyNIS: z.number().optional(),
  TotalVatFreeNIS: z.number().optional(),
  TotalNoVat: z.number().optional(),
  TotalIncludeVAT: z.number().optional(),
  VATOnly: z.number().optional(),
  TotalVatFree: z.number().optional(),
  ISORate: z.number().optional(),
  Cust_City: z.string().nullable().nullish(),
  Cust_Addres_Line1: z.string().nullable().nullish(),
  Cust_Addres_Line2: z.string().nullable().nullish(),
  Cust_LinePH: z.string().nullable().nullish(),
  Cust_MobilePH: z.string().nullable().nullish(),
  Comp_ID: z.string().nullable().nullish(),
  Email: z.string().nullable().nullish(),
  Cust_Name: z.string().nullable().nullish(),
  InvoiceDateOnly: z.date().optional(),
  InvoiceDate: z.date().optional(),
  Invoice_Number: z.int().optional(),
  InvoiceType: z.int().optional(),
  Terminal_Number: z.int().optional(),
  CoinID: z.int().optional(),
  DepartmentID: z.int().optional(),
  IsOpen: z.boolean().optional(),
  ValueDate: z.date().optional(),
  UserID: z.int().nullable().nullish(),
  Customer_Number: z.int().nullable().nullish(),
  group_number: z.int().nullable().nullish(),
  Languge: z.string().nullable().nullish(),
  UserComments: z.string().nullable().nullish(),
  Discount: z.number().nullable().nullish(),
  DiscountNIS: z.number().nullable().nullish(),
  ValidateItemsisPriceIncludeVat: z.boolean().nullable().nullish(),
  ExternalId: z.string().nullable().nullish(),
  ZReport: z.int().nullable().nullish(),
  Asmachta: z.string().nullable().nullish(),
  SumBeforeDiscountNIS: z.number().optional(),
  TotalChashNIS: z.number().optional(),
  TotalChequesNIS: z.number().optional(),
  TotalCreditCardNIS: z.number().optional(),
  TotalCustomeTransactionNIS: z.number().optional(),
  TotalRicipientNIS: z.number().optional(),
  TotalChash: z.number().optional(),
  TotalCheques: z.number().optional(),
  IsNegetive: z.boolean().optional(),
  TotalCreditCard: z.number().optional(),
  TotalCustomeTransaction: z.number().optional(),
  TotalRicipient: z.number().optional(),
}) as unknown as ToZod<InvHeadLineDto>